# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

codecov:
  # Require CI to pass before providing coverage report
  require_ci_to_pass: true
  
  # Notify settings
  notify:
    # Wait for CI to finish
    wait_for_ci: true

# Coverage settings
coverage:
  # Precision for coverage percentage
  precision: 2
  
  # Round coverage to nearest integer
  round: down
  
  # Coverage range (red to green)
  range: "70...95"
  
  # Status checks
  status:
    # Project coverage
    project:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error
    
    # Patch coverage for new code
    patch:
      default:
        target: 85%
        threshold: 1%
        if_ci_failed: error

# Comment settings for pull requests
comment:
  # Layout of the comment
  layout: "reach, diff, flags, files, footer"
  
  # Behavior when comment exists
  behavior: default
  
  # Require changes to post comment
  require_changes: false
  
  # Require base coverage
  require_base: no
  
  # Require head coverage
  require_head: yes

# Ignore paths
ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/__tests__/**"
  - "**/test-utils/**"
  - "**/testing/**"
  - "**/coverage/**"
  - "**/node_modules/**"
  - "**/.next/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/*.config.js"
  - "**/*.config.ts"
  - "**/jest.setup.js"
  - "**/playwright.config.ts"
  - "**/.github/**"
  - "**/public/**"
  - "**/*.md"

# Flags for different test types
flags:
  unittests:
    paths:
      - components/
      - lib/
      - hooks/
      - utils/
      - contexts/
      - services/
  
  integration:
    paths:
      - app/api/
      - lib/
      - services/

# Pull request comment template
comment:
  layout: "header, diff, flags, files, footer"
  hide_project_coverage: false