name: Deploy to Production

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

env:
  NODE_VERSION: '18'

jobs:
  # Run CI checks before deployment
  pre-deploy-checks:
    name: Pre-deployment Checks
    uses: ./.github/workflows/ci.yml

  # Build and prepare for deployment
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: pre-deploy-checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            .next/
            public/
            package.json
            package-lock.json

  # Run smoke tests
  smoke-tests:
    name: Smoke Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          npm run test:ci
          npm run lint

  # Post-deployment monitoring
  post-deploy-monitoring:
    name: Post-deployment Monitoring
    runs-on: ubuntu-latest
    needs: [build, smoke-tests]
    if: success()
    steps:
      - name: Update monitoring
        run: |
          echo "Deployment completed successfully"
          echo "Version: ${{ github.sha }}"
          echo "Time: $(date)"

      - name: Run Lighthouse audit
        run: |
          npm install -g @lhci/cli@0.12.x
          echo "Lighthouse audit would run here for production URL"

      - name: Notify deployment
        if: always()
        run: |
          echo "Deployment notification:"
          echo "Status: ${{ job.status }}"
          echo "Version: ${{ github.sha }}"